# Generated by Django 3.0.8 on 2020-09-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bids_by',
            new_name='bidder',
        ),
    ]
