# Generated by Django 3.0.8 on 2020-09-12 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200912_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
        migrations.AddField(
            model_name='listing',
            name='last_bidder',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='winnings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
